swagger: '2.0'
info:
  title: Pilotos
  version: "0.1"
  description: Exemplo simples de API contendo infomrações sobre pilotos
consumes:
  - application/json
produces:
  - application/json
paths:
  /test:
    get:
      operationId: server.controllers.check_status.test
      summary: Verifica status do sistema (online ou não)
      responses:
        200:
          description: Return system status
  /pilotos:
    get:
      operationId: server.controllers.pilotos_controller.get_pilotos
      summary: retorna todos os pilotos disponiveis da API
      responses:
        "200":
          description: "sucesso"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Piloto"
    post:
      operationId: server.controllers.pilotos_controller.post_piloto
      summary: cadastra novo piloto
      parameters:
        - in: body
          name: piloto_input
          description: dados do piloto
          required: true
          schema:
            $ref: "#/definitions/PilotoInput"
      responses:
        "201":
          description: "cadastrado novo piloto"
          schema:
            type: "array"
            items:
                $ref: "#/definitions/PilotoInput"
definitions:
  PilotoInput:
    type: "object"
    properties:
      nome:
        type: "string"
      nacionalidade:
        type: "string"
      cidade_natal:
        type: "string"
      nascimento:
        type: "string"
      vitorias:
        type: "integer"
        minimum: 0
      corridas_participadas:
        type: "integer"
        minimum: 0
      pole_positions:
        type: "integer"
        minimum: 0
      voltas_mais_rapidas:
        type: "integer"
        minimum: 0
      podios:
        type: "integer"
        minimum: 0
      biografia:
        type: "string"
  Piloto:
    type: "object"
    properties:
      id:
        type: "integer"
      nome:
        type: "string"
      nacionalidade:
        type: "string"
      cidade_natal:
        type: "string"
      nascimento:
        type: "string"
      vitorias:
        type: "integer"
        minimum: 0
      corridas_participadas:
        type: "integer"
        minimum: 0
      pole_positions:
        type: "integer"
        minimum: 0
      voltas_mais_rapidas:
        type: "integer"
        minimum: 0
      podios:
        type: "integer"
        minimum: 0
      biografia:
        type: "string"
